// Profile-driven, non-interactive provisioning.
//
// `envsetup apply <profile.yml>` reads a private YAML profile and regenerates
// the gitignored "local" files that hold personal/employer-specific details
// the repo deliberately keeps out of version control:
//
//	git:                      -> git/identity.local
//	  name / email
//	env:                      -> .env   (overlaid onto .env.example, 0600)
//	  KEY: value …
//	zsh:                      -> zsh/local.zsh
//	  GOPRIVATE / extra
//
// The profile is the source of truth: any section it provides is (re)written
// verbatim. Sections it omits are left untouched. It is invoked by install.sh
// when DOTFILES_PROFILE points at a readable file, so a fresh machine can be
// provisioned end-to-end without any interactive prompts.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// profile is the on-disk schema of a private dotfiles profile.
type profile struct {
	Git struct {
		Name  string `yaml:"name"`
		Email string `yaml:"email"`
	} `yaml:"git"`
	Env map[string]string `yaml:"env"`
	Zsh struct {
		GOPRIVATE string `yaml:"GOPRIVATE"`
		Extra     string `yaml:"extra"`
	} `yaml:"zsh"`
}

// runApply loads the YAML profile and writes the local files it describes.
// It returns an error (non-zero exit) so install.sh can fall back gracefully.
func runApply(profilePath string) error {
	base := baseDir()

	raw, err := os.ReadFile(profilePath)
	if err != nil {
		return fmt.Errorf("read profile: %w", err)
	}

	var p profile
	if err := yaml.Unmarshal(raw, &p); err != nil {
		return fmt.Errorf("parse YAML profile: %w", err)
	}

	var written []string

	// git/identity.local — only when both name and email are present.
	if p.Git.Name != "" && p.Git.Email != "" {
		path := filepath.Join(base, "git", "identity.local")
		content := fmt.Sprintf(
			"# Generated by envsetup from your dotfiles profile.\n[user]\n\tname = %s\n\temail = %s\n",
			p.Git.Name, p.Git.Email,
		)
		if err := writeFileAtomic(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write identity.local: %w", err)
		}
		written = append(written, "git/identity.local")
	}

	// .env — overlay profile values onto the .env.example template. Write when
	// the profile provides any env values, or when .env doesn't yet exist.
	envPath := filepath.Join(base, ".env")
	if len(p.Env) > 0 || !fileExists(envPath) {
		examplePath := filepath.Join(base, ".env.example")
		if err := writeEnvFromProfile(examplePath, envPath, p.Env); err != nil {
			return fmt.Errorf("write .env: %w", err)
		}
		written = append(written, ".env")
	}

	// zsh/local.zsh — only when GOPRIVATE or an extra block is provided.
	if p.Zsh.GOPRIVATE != "" || strings.TrimSpace(p.Zsh.Extra) != "" {
		path := filepath.Join(base, "zsh", "local.zsh")
		if err := writeFileAtomic(path, []byte(buildLocalZsh(p.Zsh.GOPRIVATE, p.Zsh.Extra)), 0o644); err != nil {
			return fmt.Errorf("write local.zsh: %w", err)
		}
		written = append(written, "zsh/local.zsh")
	}

	if len(written) == 0 {
		fmt.Fprintf(os.Stderr, "envsetup: profile %s contained no recognized values; nothing written\n", profilePath)
		return nil
	}
	fmt.Fprintf(os.Stderr, "envsetup: wrote %s from %s\n", strings.Join(written, ", "), profilePath)
	return nil
}

// writeEnvFromProfile renders .env from the .env.example template (preserving
// its header, key order, and reference defaults like OPENAI_API_KEY=$GOCODE…),
// overlaying any values supplied in the profile's env map. Profile-only keys
// not present in the template are appended in sorted order.
func writeEnvFromProfile(examplePath, envPath string, env map[string]string) error {
	vars, header, err := parseTemplate(examplePath)
	if err != nil {
		// No template available: synthesize purely from the profile.
		if len(env) == 0 {
			return err
		}
		header = "# Generated by envsetup from your dotfiles profile.\n"
		vars = nil
	}

	values := make(map[string]string, len(vars)+len(env))
	seen := make(map[string]bool, len(vars))
	for _, v := range vars {
		seen[v.key] = true
		if val, ok := env[v.key]; ok {
			values[v.key] = val
		} else {
			values[v.key] = v.defaultValue
		}
	}

	var extras []string
	for k := range env {
		if !seen[k] {
			extras = append(extras, k)
		}
	}
	sort.Strings(extras)
	for _, k := range extras {
		vars = append(vars, envVar{key: k, defaultValue: env[k]})
		values[k] = env[k]
	}

	return writeEnvAtomic(envPath, header, vars, values)
}

// buildLocalZsh renders zsh/local.zsh from the profile's GOPRIVATE value and a
// verbatim extra block (aliases, PATH shims, etc.).
func buildLocalZsh(goprivate, extra string) string {
	var b strings.Builder
	b.WriteString("# Machine/employer-specific shell config (gitignored).\n")
	b.WriteString("# Generated by envsetup from your dotfiles profile.\n")

	if goprivate != "" {
		b.WriteString("\n# Private Go module orgs\n")
		b.WriteString("export GOPRIVATE=" + goprivate + "\n")
	}

	if e := strings.Trim(extra, "\n"); strings.TrimSpace(e) != "" {
		b.WriteString("\n")
		b.WriteString(e)
		b.WriteString("\n")
	}
	return b.String()
}

// writeFileAtomic writes data to a temp file in the destination directory then
// renames it into place, so readers never observe a partial file.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, ".envsetup.tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		if tmpName != "" {
			_ = os.Remove(tmpName)
		}
	}()

	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	if err := os.Rename(tmpName, path); err != nil {
		return err
	}
	tmpName = ""
	return nil
}

// fileExists reports whether path exists and is a regular file.
func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
