" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

set showtabline=1

set guioptions=egmrt
set guioptions-=r
set nu

color solarized
