" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

set guioptions=egmrt
set guioptions-=r
set nu

color molokai

" Don't show tabs
set showtabline=0

" Make the current window big, but leave others context
set winminwidth=10
set winwidth=84
" We have to have a winheight bigger than we want to set winminheight. But
" if we set winheight to be huge before winminheight, the winminheight set will fail.
set winheight=20
set winminheight=20
set winheight=999
