" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

set guioptions=egmrt
set guioptions-=r
set nu

color molokai

" Don't show tabs
set showtabline=0
