call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin indent on

" Leader key
let mapleader = '\'

" Git stuff
set laststatus=2
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
nnoremap <leader>gs :Gstatus<cr>

" Make the current window big, but leave others context
set winminwidth=10
set winwidth=84
" We have to have a winheight bigger than we want to set winminheight. But
" if we set winheight to be huge before winminheight, the winminheight set will fail.
set winheight=5
set winminheight=5
set winheight=999

" Allow sweet hacks
set nocompatible

set encoding=utf-8
set scrolloff=3
set number
set numberwidth=4
set mousehide
set nowrap
set cursorline
set visualbell
set showcmd
set showmode
set autoindent
set tabstop=4
set shiftwidth=4
set smarttab
set ts=4 sw=4

" Persistent Undo
set undofile

" Temp Folders
set undodir=~/.tmp/
set backupdir=~/.tmp/
set directory=~/.tmp/

" Always show tabs
set showtabline=2

" Search
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch

" leader-space to clear search results
nnoremap <leader><space> :noh<cr>

" tab key to find matching bracket
nnoremap <tab> %
vnoremap <tab> %

" Color Scheme
syntax on
set guifont=MesloLGLDZ:h12
color ir_black

" Status line gnarliness
" set laststatus=2
" set statusline=%F%m%r%h%w\ (%{&ff}){%Y}\ [%l,%v][%p%%]

" Ctrlp
let g:ctrlp_max_depth = 5
map <C-P> :CtrlP <CR>

" Ignore these directories
let g:ctrlp_custom_ignore = 'node_modules'

" Look for nearest src folder
let g:ctrlp_root_markers = ['index.php']
let g:ctrlp_working_path_mode = 2

" Custom Tab Label
set guitablabel=%t

" Wildcard ignores
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*.so,*.un,*.un~,.DS_store,*.swp

" Autosave on focus lost
au FocusLost * :silent! wa!
au BufLeave * :silent! wa!

" Relative line numbers
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc
nnoremap <C-n> :call NumberToggle()<cr>

" Toggle relative line numbers
autocmd BufReadPost * :set relativenumber
autocmd BufNewFile * :set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

" Create a new vertical split and switch to it
nnoremap <leader>w <C-w>v<C-w>l

" Duplicate current line below and replace with equal signs
nnoremap <leader>1 yypVr=

" Quick editing of .vimrc
nnoremap <leader>rc <C-w><C-v><C-l>:e $MYVIMRC<cr>

" Bubble single lines
nmap <C-k> [e
nmap <C-j> ]e

" Bubble multiple lines
vmap <C-k> [egv
vmap <C-j> ]egv

" Rename Current File
function! RenameFile()
	let old_name = expand('%')
	let new_name = input('New file name: ', expand('%'))
	if new_name != '' && new_name != old_name
		exec ':saveas ' . new_name
		exec ':silent !rm ' . old_name
		redraw!
	endif
endfunction
map <leader>n :call RenameFile()<cr>

