#!/bin/bash

knnktr-gotoproject () {
	PROJECTDIR=`cat $HOME/.dotfiles/knnktr/.env`
	cd `cat $HOME/.dotfiles/knnktr/.env`
}

gg () {
	echo 'project has not been set'
}

kp() {
	clear
	knnktr-projects.js            # call node script
	if [ $? -eq 0 ]; then
		knnktr-gotoproject
		clear
		knnktr-current-project.js   # echo the project details
		knnktr-env                  # set environment aliases
	fi
}

knnktr-go-home () {
	cd $PROJECTDIR
	knnktr-current-project.js
}

knnktr-env () {
	alias home=knnktr-go-home # Alias for project root
	alias gg=knnktr-go-home	  # Alias for project root
}
