#!/bin/bash

knnktr-gotoproject () {
	PROJECTDIR=`cat $HOME/.dotfiles/knnktr/.env`
	cd `cat $HOME/.dotfiles/knnktr/.env`
}

kp() {
	clear
	knnktr-projects.js 			# call node script
	if [ $? -eq 0 ]; then
		knnktr-gotoproject
		clear
		knnktr-current-project.js 	# echo the project details
		knnktr-env					# set environment aliases
	fi
}

knnktr-go-home () {
	#clear
	cd $PROJECTDIR
	#knnktr-current-project.js
}

knnktr () {
	clear
	knnktr-help.js
}

knnktr-env () {
	# basic aliases
	alias home=knnktr-go-home				# Alias for going home
	alias gg=knnktr-go-home					# Alias for going home
	alias kk=knnktr-go-home					# Alias for going home
	alias build=knnktr-build				# Alias for build script
	alias deploy=knnktr-deploy				# Alias for deploy script

	# get paths from package.json
	IMGDIR=`cat $PROJECTDIR/package.json | json paths.images`
	JSDIR=`cat $PROJECTDIR/package.json | json paths.js`
	CSSDIR=`cat $PROJECTDIR/package.json | json paths.css`

	# append the project dir
	IMGDIR="$PROJECTDIR/$IMGDIR"
	JSDIR="$PROJECTDIR/$JSDIR"
	CSSDIR="$PROJECTDIR/$CSSDIR"

	# set aliases
	alias img="cd $IMGDIR"					# Alias for images directory
	alias js="cd $JSDIR"					# Alias for javascript directory
	alias css="cd $CSSDIR"					# Alias for css directory
}

knnktr-build () {
	FOO=`pwd`
	cd $PROJECTDIR
	make
	cd $FOO
}

knnktr-deploy () {
	FOO=`pwd`
	cd $PROJECTDIR
	./deploy
	cd $FOO
}
