# This is where any API keys are stored for AI tools

[[ -f $DOTFILES/.env ]] && source $DOTFILES/.env

# Claude
export ANTHROPIC_BASE_URL="https://REDACTED.example"
export ANTHROPIC_AUTH_TOKEN=$GOCODE_API_TOKEN
export ANTHROPIC_MODEL="claude-sonnet-4-6"
export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1
export CLAUDE_CODE_DISABLE_AUTO_MEMORY=1
export DISABLE_AUTOUPDATER=1

alias claude="ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN=$GOCODE_API_TOKEN claude"

# Aider
alias aider="ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL ANTHROPIC_API_KEY=$GOCODE_API_TOKEN aider --model $ANTHROPIC_MODEL"

# Codex
alias codex="OPENAI_BASE_URL=$ANTHROPIC_BASE_URL OPENAI_API_KEY=$GOCODE_API_TOKEN codex -m gpt-5-codex"
