# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.dotfiles/zsh

# Path to dotfiles
DOTFILES=$HOME/.dotfiles

# Your project folder that we can `c [tab]` to
export PROJECTS=~/Sites/knnktr

# Autoload Functions
fpath=($DOTFILES/zsh/functions $fpath)
autoload -U $DOTFILES/zsh/functions/*(:t)

# Theme ~/.oh-my-zsh/themes/
# ZSH_THEME="my-theme"
ZSH_THEME="miloshadzic"

# Set vim as editor
export EDITOR=vim

export ACK_COLOR_MATCH='red'

# Plugins ~/.oh-my-zsh/plugins/*
plugins=(git, sublime)

# https://github.com/rupa/z
. ~/.dotfiles/zsh/plugins/z.sh
function precmd () {
	_z --add "$(pwd -P)"
}

# OH-MY-ZSH
source $ZSH/oh-my-zsh.sh

# Set NODE Exports
export NODE_PATH="/usr/local/lib/node_modules"

# Use Homebrew libs before system libs
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# Append to PATH
PATH=$PATH:/opt/homebrew/bin
PATH=$PATH:$HOME/.rvm/bin 		# Add RVM to PATH for scripting
PATH=$PATH:~/.dotfiles/git/bin 	# Add git workflow scripts
#PATH=$PATH:/Users/jono/node_modules/yeoman/bin


# Import aliases
source $DOTFILES/zsh/aliases.zsh

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

unset MAILCHECK
